apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: owo7n7ctq-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/owo7n7ctq-dotnet-basic-gitops